ARG REL_TAG=latest
FROM openeuler/openeuler:$REL_TAG
RUN set -ex; \
    dnf install --installroot /mnt/rootfs --setopt install_weak_deps=false -y \
    bash-completion \
    bc \
    dbus-daemon \
    diffutils \
    hostname \
    iproute \
    iptables-nft \
    nftables \
    openssl \
    passwd \
    procps-ng \
    sudo \
    systemd-pam \
    tar \
    util-linux-user \
    vim-minimal \
    xz \
    yum; \
    dnf --installroot /mnt/rootfs clean all; \
    rm -rf /mnt/rootfs/var/cache/* /mnt/rootfs/var/log/dnf.*; \
    rm -rf /mnt/rootfs/etc/machine-id; \
    touch /mnt/rootfs/etc/machine-id; \
    touch /mnt/rootfs/etc/fstab; \
    cp /mnt/rootfs/etc/skel/.bash* /mnt/rootfs/root/; \
    sed -i '/TMOUT=300/d' /mnt/rootfs/etc/bashrc
COPY wsl.conf /mnt/rootfs/etc/wsl.conf
COPY exclude /mnt/exclude
CMD tar -zcOC /mnt/rootfs --exclude-from=/mnt/exclude .
